version: "3.1"
language: "en"  
pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 50  
  entity_recognition: true
  intent_classification: true
policies:
- name: MemoizationPolicy
- name: TEDPolicy
  epochs: 25  
assistant_id: 20250404-144355-forward-percussion
